name: ci

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Check GitHub Status
        uses: ./

  ci-fail:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Check GitHub Status
        continue-on-error: true
        uses: ./
        with:
          overall_threshold: minor
          pages_threshold: partial_outage
        env:
          GHACTION_GITHUB_STATUS_MOCKIT: true
